version: '3.9'
name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    volumes:
      - serverConfig:/config

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

volumes:
  serverConfig:
    driver: local
    driver_opts:
      type: none
      device: ./server/config
      o: bind
  clientConfig:
    driver: local
    driver_opts:
      type: none
      device: ./client/config
      o: bind
